import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :nostr_backend, NostrBackendWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

# Enhanced logger format for production to include request information
config :logger, :console,
  format: "[$level] $message\n",
  metadata: [:request_id, :method, :path, :query_string]

# Disable Phoenix's built-in request logging since we have our custom RequestLogger
config :phoenix, :logger, false

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
