services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        GIT_VERSION: ${GIT_VERSION:-}
    env_file:
      - .env
    volumes:
      - ./:/app
    ports:
      - "4000:4000"

