"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Queue Server API
 * A secure, privacy-preserving queue server for newsletter jobs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.DefaultApi = exports.DefaultApiFactory = exports.DefaultApiFp = exports.DefaultApiAxiosParamCreator = exports.CampaignCreateEncAlgEnum = void 0;
const axios_1 = require("axios");
// Some imports not used depending on template conditions
// @ts-ignore
const common_1 = require("./common");
// @ts-ignore
const base_1 = require("./base");
exports.CampaignCreateEncAlgEnum = {
    Nip44: 'nip44',
    Plain: 'plain'
};
/**
 * DefaultApi - axios parameter creator
 * @export
 */
const DefaultApiAxiosParamCreator = function (configuration) {
    return {
        /**
         *
         * @summary Bulk enqueue jobs (NDJSON)
         * @param {string} id Campaign ID
         * @param {string} body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkEnqueueJobs: (id_1, body_1, ...args_1) => __awaiter(this, [id_1, body_1, ...args_1], void 0, function* (id, body, options = {}) {
            // verify required parameter 'id' is not null or undefined
            (0, common_1.assertParamExists)('bulkEnqueueJobs', 'id', id);
            // verify required parameter 'body' is not null or undefined
            (0, common_1.assertParamExists)('bulkEnqueueJobs', 'body', body);
            const localVarPath = `/campaigns/{id}/jobs/bulk`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, common_1.DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign(Object.assign({ method: 'POST' }, baseOptions), options);
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            // authentication BearerAuth required
            // http bearer authentication required
            yield (0, common_1.setBearerAuthToObject)(localVarHeaderParameter, configuration);
            localVarHeaderParameter['Content-Type'] = 'application/x-ndjson';
            (0, common_1.setSearchParams)(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = Object.assign(Object.assign(Object.assign({}, localVarHeaderParameter), headersFromBaseOptions), options.headers);
            localVarRequestOptions.data = (0, common_1.serializeDataIfNeeded)(body, localVarRequestOptions, configuration);
            return {
                url: (0, common_1.toPathString)(localVarUrlObj),
                options: localVarRequestOptions,
            };
        }),
        /**
         *
         * @summary Commit campaign uploads and enable processing
         * @param {string} id Campaign ID
         * @param {CommitRequest} [commitRequest]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        commitCampaign: (id_1, commitRequest_1, ...args_1) => __awaiter(this, [id_1, commitRequest_1, ...args_1], void 0, function* (id, commitRequest, options = {}) {
            // verify required parameter 'id' is not null or undefined
            (0, common_1.assertParamExists)('commitCampaign', 'id', id);
            const localVarPath = `/campaigns/{id}/commit`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, common_1.DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign(Object.assign({ method: 'PATCH' }, baseOptions), options);
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            // authentication BearerAuth required
            // http bearer authentication required
            yield (0, common_1.setBearerAuthToObject)(localVarHeaderParameter, configuration);
            localVarHeaderParameter['Content-Type'] = 'application/json';
            (0, common_1.setSearchParams)(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = Object.assign(Object.assign(Object.assign({}, localVarHeaderParameter), headersFromBaseOptions), options.headers);
            localVarRequestOptions.data = (0, common_1.serializeDataIfNeeded)(commitRequest, localVarRequestOptions, configuration);
            return {
                url: (0, common_1.toPathString)(localVarUrlObj),
                options: localVarRequestOptions,
            };
        }),
        /**
         *
         * @summary Create campaign
         * @param {CampaignCreate} campaignCreate
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCampaign: (campaignCreate_1, ...args_1) => __awaiter(this, [campaignCreate_1, ...args_1], void 0, function* (campaignCreate, options = {}) {
            // verify required parameter 'campaignCreate' is not null or undefined
            (0, common_1.assertParamExists)('createCampaign', 'campaignCreate', campaignCreate);
            const localVarPath = `/campaigns`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, common_1.DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign(Object.assign({ method: 'POST' }, baseOptions), options);
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            // authentication BearerAuth required
            // http bearer authentication required
            yield (0, common_1.setBearerAuthToObject)(localVarHeaderParameter, configuration);
            localVarHeaderParameter['Content-Type'] = 'application/json';
            (0, common_1.setSearchParams)(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = Object.assign(Object.assign(Object.assign({}, localVarHeaderParameter), headersFromBaseOptions), options.headers);
            localVarRequestOptions.data = (0, common_1.serializeDataIfNeeded)(campaignCreate, localVarRequestOptions, configuration);
            return {
                url: (0, common_1.toPathString)(localVarUrlObj),
                options: localVarRequestOptions,
            };
        }),
        /**
         *
         * @summary Get campaign status
         * @param {string} id Campaign ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCampaignStatus: (id_1, ...args_1) => __awaiter(this, [id_1, ...args_1], void 0, function* (id, options = {}) {
            // verify required parameter 'id' is not null or undefined
            (0, common_1.assertParamExists)('getCampaignStatus', 'id', id);
            const localVarPath = `/campaigns/{id}/status`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, common_1.DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign(Object.assign({ method: 'GET' }, baseOptions), options);
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            // authentication BearerAuth required
            // http bearer authentication required
            yield (0, common_1.setBearerAuthToObject)(localVarHeaderParameter, configuration);
            (0, common_1.setSearchParams)(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = Object.assign(Object.assign(Object.assign({}, localVarHeaderParameter), headersFromBaseOptions), options.headers);
            return {
                url: (0, common_1.toPathString)(localVarUrlObj),
                options: localVarRequestOptions,
            };
        }),
        /**
         *
         * @summary Get campaign status by external ID
         * @param {string} externalId External ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCampaignStatusByExternalId: (externalId_1, ...args_1) => __awaiter(this, [externalId_1, ...args_1], void 0, function* (externalId, options = {}) {
            // verify required parameter 'externalId' is not null or undefined
            (0, common_1.assertParamExists)('getCampaignStatusByExternalId', 'externalId', externalId);
            const localVarPath = `/campaigns/external/{external_id}/status`
                .replace(`{${"external_id"}}`, encodeURIComponent(String(externalId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, common_1.DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign(Object.assign({ method: 'GET' }, baseOptions), options);
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            // authentication BearerAuth required
            // http bearer authentication required
            yield (0, common_1.setBearerAuthToObject)(localVarHeaderParameter, configuration);
            (0, common_1.setSearchParams)(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = Object.assign(Object.assign(Object.assign({}, localVarHeaderParameter), headersFromBaseOptions), options.headers);
            return {
                url: (0, common_1.toPathString)(localVarUrlObj),
                options: localVarRequestOptions,
            };
        }),
    };
};
exports.DefaultApiAxiosParamCreator = DefaultApiAxiosParamCreator;
/**
 * DefaultApi - functional programming interface
 * @export
 */
const DefaultApiFp = function (configuration) {
    const localVarAxiosParamCreator = (0, exports.DefaultApiAxiosParamCreator)(configuration);
    return {
        /**
         *
         * @summary Bulk enqueue jobs (NDJSON)
         * @param {string} id Campaign ID
         * @param {string} body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkEnqueueJobs(id, body, options) {
            return __awaiter(this, void 0, void 0, function* () {
                var _a, _b, _c;
                const localVarAxiosArgs = yield localVarAxiosParamCreator.bulkEnqueueJobs(id, body, options);
                const localVarOperationServerIndex = (_a = configuration === null || configuration === void 0 ? void 0 : configuration.serverIndex) !== null && _a !== void 0 ? _a : 0;
                const localVarOperationServerBasePath = (_c = (_b = base_1.operationServerMap['DefaultApi.bulkEnqueueJobs']) === null || _b === void 0 ? void 0 : _b[localVarOperationServerIndex]) === null || _c === void 0 ? void 0 : _c.url;
                return (axios, basePath) => (0, common_1.createRequestFunction)(localVarAxiosArgs, axios_1.default, base_1.BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
            });
        },
        /**
         *
         * @summary Commit campaign uploads and enable processing
         * @param {string} id Campaign ID
         * @param {CommitRequest} [commitRequest]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        commitCampaign(id, commitRequest, options) {
            return __awaiter(this, void 0, void 0, function* () {
                var _a, _b, _c;
                const localVarAxiosArgs = yield localVarAxiosParamCreator.commitCampaign(id, commitRequest, options);
                const localVarOperationServerIndex = (_a = configuration === null || configuration === void 0 ? void 0 : configuration.serverIndex) !== null && _a !== void 0 ? _a : 0;
                const localVarOperationServerBasePath = (_c = (_b = base_1.operationServerMap['DefaultApi.commitCampaign']) === null || _b === void 0 ? void 0 : _b[localVarOperationServerIndex]) === null || _c === void 0 ? void 0 : _c.url;
                return (axios, basePath) => (0, common_1.createRequestFunction)(localVarAxiosArgs, axios_1.default, base_1.BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
            });
        },
        /**
         *
         * @summary Create campaign
         * @param {CampaignCreate} campaignCreate
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCampaign(campaignCreate, options) {
            return __awaiter(this, void 0, void 0, function* () {
                var _a, _b, _c;
                const localVarAxiosArgs = yield localVarAxiosParamCreator.createCampaign(campaignCreate, options);
                const localVarOperationServerIndex = (_a = configuration === null || configuration === void 0 ? void 0 : configuration.serverIndex) !== null && _a !== void 0 ? _a : 0;
                const localVarOperationServerBasePath = (_c = (_b = base_1.operationServerMap['DefaultApi.createCampaign']) === null || _b === void 0 ? void 0 : _b[localVarOperationServerIndex]) === null || _c === void 0 ? void 0 : _c.url;
                return (axios, basePath) => (0, common_1.createRequestFunction)(localVarAxiosArgs, axios_1.default, base_1.BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
            });
        },
        /**
         *
         * @summary Get campaign status
         * @param {string} id Campaign ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCampaignStatus(id, options) {
            return __awaiter(this, void 0, void 0, function* () {
                var _a, _b, _c;
                const localVarAxiosArgs = yield localVarAxiosParamCreator.getCampaignStatus(id, options);
                const localVarOperationServerIndex = (_a = configuration === null || configuration === void 0 ? void 0 : configuration.serverIndex) !== null && _a !== void 0 ? _a : 0;
                const localVarOperationServerBasePath = (_c = (_b = base_1.operationServerMap['DefaultApi.getCampaignStatus']) === null || _b === void 0 ? void 0 : _b[localVarOperationServerIndex]) === null || _c === void 0 ? void 0 : _c.url;
                return (axios, basePath) => (0, common_1.createRequestFunction)(localVarAxiosArgs, axios_1.default, base_1.BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
            });
        },
        /**
         *
         * @summary Get campaign status by external ID
         * @param {string} externalId External ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCampaignStatusByExternalId(externalId, options) {
            return __awaiter(this, void 0, void 0, function* () {
                var _a, _b, _c;
                const localVarAxiosArgs = yield localVarAxiosParamCreator.getCampaignStatusByExternalId(externalId, options);
                const localVarOperationServerIndex = (_a = configuration === null || configuration === void 0 ? void 0 : configuration.serverIndex) !== null && _a !== void 0 ? _a : 0;
                const localVarOperationServerBasePath = (_c = (_b = base_1.operationServerMap['DefaultApi.getCampaignStatusByExternalId']) === null || _b === void 0 ? void 0 : _b[localVarOperationServerIndex]) === null || _c === void 0 ? void 0 : _c.url;
                return (axios, basePath) => (0, common_1.createRequestFunction)(localVarAxiosArgs, axios_1.default, base_1.BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
            });
        },
    };
};
exports.DefaultApiFp = DefaultApiFp;
/**
 * DefaultApi - factory interface
 * @export
 */
const DefaultApiFactory = function (configuration, basePath, axios) {
    const localVarFp = (0, exports.DefaultApiFp)(configuration);
    return {
        /**
         *
         * @summary Bulk enqueue jobs (NDJSON)
         * @param {string} id Campaign ID
         * @param {string} body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkEnqueueJobs(id, body, options) {
            return localVarFp.bulkEnqueueJobs(id, body, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Commit campaign uploads and enable processing
         * @param {string} id Campaign ID
         * @param {CommitRequest} [commitRequest]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        commitCampaign(id, commitRequest, options) {
            return localVarFp.commitCampaign(id, commitRequest, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Create campaign
         * @param {CampaignCreate} campaignCreate
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCampaign(campaignCreate, options) {
            return localVarFp.createCampaign(campaignCreate, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Get campaign status
         * @param {string} id Campaign ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCampaignStatus(id, options) {
            return localVarFp.getCampaignStatus(id, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Get campaign status by external ID
         * @param {string} externalId External ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCampaignStatusByExternalId(externalId, options) {
            return localVarFp.getCampaignStatusByExternalId(externalId, options).then((request) => request(axios, basePath));
        },
    };
};
exports.DefaultApiFactory = DefaultApiFactory;
/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
class DefaultApi extends base_1.BaseAPI {
    /**
     *
     * @summary Bulk enqueue jobs (NDJSON)
     * @param {string} id Campaign ID
     * @param {string} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    bulkEnqueueJobs(id, body, options) {
        return (0, exports.DefaultApiFp)(this.configuration).bulkEnqueueJobs(id, body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary Commit campaign uploads and enable processing
     * @param {string} id Campaign ID
     * @param {CommitRequest} [commitRequest]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    commitCampaign(id, commitRequest, options) {
        return (0, exports.DefaultApiFp)(this.configuration).commitCampaign(id, commitRequest, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary Create campaign
     * @param {CampaignCreate} campaignCreate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    createCampaign(campaignCreate, options) {
        return (0, exports.DefaultApiFp)(this.configuration).createCampaign(campaignCreate, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary Get campaign status
     * @param {string} id Campaign ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    getCampaignStatus(id, options) {
        return (0, exports.DefaultApiFp)(this.configuration).getCampaignStatus(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary Get campaign status by external ID
     * @param {string} externalId External ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    getCampaignStatusByExternalId(externalId, options) {
        return (0, exports.DefaultApiFp)(this.configuration).getCampaignStatusByExternalId(externalId, options).then((request) => request(this.axios, this.basePath));
    }
}
exports.DefaultApi = DefaultApi;
