/**
 * Queue Server API
 * A secure, privacy-preserving queue server for newsletter jobs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import type { RequestArgs } from './base';
import { BaseAPI } from './base';
/**
 *
 * @export
 * @interface BulkResult
 */
export interface BulkResult {
    /**
     *
     * @type {number}
     * @memberof BulkResult
     */
    'accepted': number;
    /**
     *
     * @type {number}
     * @memberof BulkResult
     */
    'duplicates': number;
    /**
     *
     * @type {number}
     * @memberof BulkResult
     */
    'errors': number;
    /**
     *
     * @type {string}
     * @memberof BulkResult
     */
    'last_id'?: string | null;
}
/**
 *
 * @export
 * @interface CampaignCreate
 */
export interface CampaignCreate {
    /**
     * NIP-44 encrypted campaign JSON (base64)
     * @type {string}
     * @memberof CampaignCreate
     */
    'ciphertext_b64'?: string;
    /**
     *
     * @type {CampaignCreateEnc}
     * @memberof CampaignCreate
     */
    'enc'?: CampaignCreateEnc;
    /**
     * Client-assigned idempotency key for the campaign
     * @type {string}
     * @memberof CampaignCreate
     */
    'externalId'?: string;
    /**
     *
     * @type {string}
     * @memberof CampaignCreate
     */
    'ownerId': string;
    /**
     *
     * @type {string}
     * @memberof CampaignCreate
     */
    'queue': string;
    /**
     *
     * @type {number}
     * @memberof CampaignCreate
     */
    'size_bytes'?: number;
}
/**
 *
 * @export
 * @interface CampaignCreateEnc
 */
export interface CampaignCreateEnc {
    /**
     *
     * @type {string}
     * @memberof CampaignCreateEnc
     */
    'alg': CampaignCreateEncAlgEnum;
    /**
     *
     * @type {string}
     * @memberof CampaignCreateEnc
     */
    'kid'?: string | null;
}
export declare const CampaignCreateEncAlgEnum: {
    readonly Nip44: "nip44";
    readonly Plain: "plain";
};
export type CampaignCreateEncAlgEnum = typeof CampaignCreateEncAlgEnum[keyof typeof CampaignCreateEncAlgEnum];
/**
 *
 * @export
 * @interface CampaignCreateResponse
 */
export interface CampaignCreateResponse {
    /**
     * Server-generated numeric ID as string
     * @type {string}
     * @memberof CampaignCreateResponse
     */
    'campaign_id': string;
}
/**
 *
 * @export
 * @interface CampaignStatus
 */
export interface CampaignStatus {
    /**
     *
     * @type {string}
     * @memberof CampaignStatus
     */
    'campaign_id': string;
    /**
     *
     * @type {CampaignStatusCounts}
     * @memberof CampaignStatus
     */
    'counts': CampaignStatusCounts;
    /**
     *
     * @type {number}
     * @memberof CampaignStatus
     */
    'expected_jobs'?: number | null;
    /**
     *
     * @type {string}
     * @memberof CampaignStatus
     */
    'state'?: string;
    /**
     *
     * @type {string}
     * @memberof CampaignStatus
     */
    'updated_at': string;
    /**
     *
     * @type {number}
     * @memberof CampaignStatus
     */
    'uploaded_jobs'?: number;
}
/**
 *
 * @export
 * @interface CampaignStatusCounts
 */
export interface CampaignStatusCounts {
    /**
     *
     * @type {number}
     * @memberof CampaignStatusCounts
     */
    'available': number;
    /**
     *
     * @type {number}
     * @memberof CampaignStatusCounts
     */
    'done': number;
    /**
     *
     * @type {number}
     * @memberof CampaignStatusCounts
     */
    'failed': number;
    /**
     *
     * @type {number}
     * @memberof CampaignStatusCounts
     */
    'leased': number;
    /**
     *
     * @type {number}
     * @memberof CampaignStatusCounts
     */
    'retryable': number;
}
/**
 *
 * @export
 * @interface CommitRequest
 */
export interface CommitRequest {
    /**
     *
     * @type {number}
     * @memberof CommitRequest
     */
    'expected_jobs'?: number;
}
/**
 *
 * @export
 * @interface CommitResponse
 */
export interface CommitResponse {
    /**
     *
     * @type {string}
     * @memberof CommitResponse
     */
    'campaign_id': string;
    /**
     *
     * @type {number}
     * @memberof CommitResponse
     */
    'expected_jobs': number;
    /**
     *
     * @type {string}
     * @memberof CommitResponse
     */
    'state': string;
}
/**
 *
 * @export
 * @interface ErrorResponse
 */
export interface ErrorResponse {
    /**
     *
     * @type {ErrorResponseError}
     * @memberof ErrorResponse
     */
    'error': ErrorResponseError;
}
/**
 *
 * @export
 * @interface ErrorResponseError
 */
export interface ErrorResponseError {
    /**
     *
     * @type {string}
     * @memberof ErrorResponseError
     */
    'code': string;
    /**
     *
     * @type {string}
     * @memberof ErrorResponseError
     */
    'message': string;
}
/**
 * DefaultApi - axios parameter creator
 * @export
 */
export declare const DefaultApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @summary Bulk enqueue jobs (NDJSON)
     * @param {string} id Campaign ID
     * @param {string} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    bulkEnqueueJobs: (id: string, body: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Commit campaign uploads and enable processing
     * @param {string} id Campaign ID
     * @param {CommitRequest} [commitRequest]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    commitCampaign: (id: string, commitRequest?: CommitRequest, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Create campaign
     * @param {CampaignCreate} campaignCreate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createCampaign: (campaignCreate: CampaignCreate, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Get campaign status
     * @param {string} id Campaign ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getCampaignStatus: (id: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Get campaign status by external ID
     * @param {string} externalId External ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getCampaignStatusByExternalId: (externalId: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
};
/**
 * DefaultApi - functional programming interface
 * @export
 */
export declare const DefaultApiFp: (configuration?: Configuration) => {
    /**
     *
     * @summary Bulk enqueue jobs (NDJSON)
     * @param {string} id Campaign ID
     * @param {string} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    bulkEnqueueJobs(id: string, body: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BulkResult>>;
    /**
     *
     * @summary Commit campaign uploads and enable processing
     * @param {string} id Campaign ID
     * @param {CommitRequest} [commitRequest]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    commitCampaign(id: string, commitRequest?: CommitRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommitResponse>>;
    /**
     *
     * @summary Create campaign
     * @param {CampaignCreate} campaignCreate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createCampaign(campaignCreate: CampaignCreate, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CampaignCreateResponse>>;
    /**
     *
     * @summary Get campaign status
     * @param {string} id Campaign ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getCampaignStatus(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CampaignStatus>>;
    /**
     *
     * @summary Get campaign status by external ID
     * @param {string} externalId External ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getCampaignStatusByExternalId(externalId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CampaignStatus>>;
};
/**
 * DefaultApi - factory interface
 * @export
 */
export declare const DefaultApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @summary Bulk enqueue jobs (NDJSON)
     * @param {string} id Campaign ID
     * @param {string} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    bulkEnqueueJobs(id: string, body: string, options?: RawAxiosRequestConfig): AxiosPromise<BulkResult>;
    /**
     *
     * @summary Commit campaign uploads and enable processing
     * @param {string} id Campaign ID
     * @param {CommitRequest} [commitRequest]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    commitCampaign(id: string, commitRequest?: CommitRequest, options?: RawAxiosRequestConfig): AxiosPromise<CommitResponse>;
    /**
     *
     * @summary Create campaign
     * @param {CampaignCreate} campaignCreate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createCampaign(campaignCreate: CampaignCreate, options?: RawAxiosRequestConfig): AxiosPromise<CampaignCreateResponse>;
    /**
     *
     * @summary Get campaign status
     * @param {string} id Campaign ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getCampaignStatus(id: string, options?: RawAxiosRequestConfig): AxiosPromise<CampaignStatus>;
    /**
     *
     * @summary Get campaign status by external ID
     * @param {string} externalId External ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getCampaignStatusByExternalId(externalId: string, options?: RawAxiosRequestConfig): AxiosPromise<CampaignStatus>;
};
/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export declare class DefaultApi extends BaseAPI {
    /**
     *
     * @summary Bulk enqueue jobs (NDJSON)
     * @param {string} id Campaign ID
     * @param {string} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    bulkEnqueueJobs(id: string, body: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<BulkResult, any, {}>>;
    /**
     *
     * @summary Commit campaign uploads and enable processing
     * @param {string} id Campaign ID
     * @param {CommitRequest} [commitRequest]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    commitCampaign(id: string, commitRequest?: CommitRequest, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<CommitResponse, any, {}>>;
    /**
     *
     * @summary Create campaign
     * @param {CampaignCreate} campaignCreate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    createCampaign(campaignCreate: CampaignCreate, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<CampaignCreateResponse, any, {}>>;
    /**
     *
     * @summary Get campaign status
     * @param {string} id Campaign ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    getCampaignStatus(id: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<CampaignStatus, any, {}>>;
    /**
     *
     * @summary Get campaign status by external ID
     * @param {string} externalId External ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    getCampaignStatusByExternalId(externalId: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<CampaignStatus, any, {}>>;
}
