/* tslint:disable */
/* eslint-disable */
/**
 * Queue Server API
 * A secure, privacy-preserving queue server for newsletter jobs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface BulkResult
 */
export interface BulkResult {
    /**
     * 
     * @type {number}
     * @memberof BulkResult
     */
    'accepted': number;
    /**
     * 
     * @type {number}
     * @memberof BulkResult
     */
    'duplicates': number;
    /**
     * 
     * @type {number}
     * @memberof BulkResult
     */
    'errors': number;
    /**
     * 
     * @type {string}
     * @memberof BulkResult
     */
    'last_id'?: string | null;
}
/**
 * 
 * @export
 * @interface CampaignCreate
 */
export interface CampaignCreate {
    /**
     * NIP-44 encrypted campaign JSON (base64)
     * @type {string}
     * @memberof CampaignCreate
     */
    'ciphertext_b64'?: string;
    /**
     * 
     * @type {CampaignCreateEnc}
     * @memberof CampaignCreate
     */
    'enc'?: CampaignCreateEnc;
    /**
     * Client-assigned idempotency key for the campaign
     * @type {string}
     * @memberof CampaignCreate
     */
    'externalId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CampaignCreate
     */
    'ownerId': string;
    /**
     * 
     * @type {string}
     * @memberof CampaignCreate
     */
    'queue': string;
    /**
     * 
     * @type {number}
     * @memberof CampaignCreate
     */
    'size_bytes'?: number;
}
/**
 * 
 * @export
 * @interface CampaignCreateEnc
 */
export interface CampaignCreateEnc {
    /**
     * 
     * @type {string}
     * @memberof CampaignCreateEnc
     */
    'alg': CampaignCreateEncAlgEnum;
    /**
     * 
     * @type {string}
     * @memberof CampaignCreateEnc
     */
    'kid'?: string | null;
}

export const CampaignCreateEncAlgEnum = {
    Nip44: 'nip44',
    Plain: 'plain'
} as const;

export type CampaignCreateEncAlgEnum = typeof CampaignCreateEncAlgEnum[keyof typeof CampaignCreateEncAlgEnum];

/**
 * 
 * @export
 * @interface CampaignCreateResponse
 */
export interface CampaignCreateResponse {
    /**
     * Server-generated numeric ID as string
     * @type {string}
     * @memberof CampaignCreateResponse
     */
    'campaign_id': string;
}
/**
 * 
 * @export
 * @interface CampaignStatus
 */
export interface CampaignStatus {
    /**
     * 
     * @type {string}
     * @memberof CampaignStatus
     */
    'campaign_id': string;
    /**
     * 
     * @type {CampaignStatusCounts}
     * @memberof CampaignStatus
     */
    'counts': CampaignStatusCounts;
    /**
     * Sender-facing delivery phase
     * @type {string}
     * @memberof CampaignStatus
     */
    'delivery': CampaignStatusDeliveryEnum;
    /**
     * 
     * @type {number}
     * @memberof CampaignStatus
     */
    'expected_jobs'?: number | null;
    /**
     * 
     * @type {Array<CampaignStatusError>}
     * @memberof CampaignStatus
     */
    'recent_errors'?: Array<CampaignStatusError>;
    /**
     * 
     * @type {string}
     * @memberof CampaignStatus
     */
    'state'?: string;
    /**
     * 
     * @type {string}
     * @memberof CampaignStatus
     */
    'updated_at': string;
    /**
     * 
     * @type {number}
     * @memberof CampaignStatus
     */
    'uploaded_jobs'?: number;
}

export const CampaignStatusDeliveryEnum = {
    Queueing: 'queueing',
    Sending: 'sending',
    Sent: 'sent',
    Failed: 'failed',
    Partial: 'partial'
} as const;

export type CampaignStatusDeliveryEnum = typeof CampaignStatusDeliveryEnum[keyof typeof CampaignStatusDeliveryEnum];
/**
 * 
 * @export
 * @interface CampaignStatusCounts
 */
export interface CampaignStatusCounts {
    /**
     * 
     * @type {number}
     * @memberof CampaignStatusCounts
     */
    'available': number;
    /**
     * 
     * @type {number}
     * @memberof CampaignStatusCounts
     */
    'done': number;
    /**
     * 
     * @type {number}
     * @memberof CampaignStatusCounts
     */
    'failed': number;
    /**
     * 
     * @type {number}
     * @memberof CampaignStatusCounts
     */
    'held': number;
    /**
     * 
     * @type {number}
     * @memberof CampaignStatusCounts
     */
    'leased': number;
    /**
     * 
     * @type {number}
     * @memberof CampaignStatusCounts
     */
    'retryable': number;
}
/**
 * 
 * @export
 * @interface CampaignStatusError
 */
export interface CampaignStatusError {
    /**
     * 
     * @type {number}
     * @memberof CampaignStatusError
     */
    'attempt'?: number;
    /**
     * 
     * @type {CampaignStatusErrorError}
     * @memberof CampaignStatusError
     */
    'error'?: CampaignStatusErrorError;
    /**
     * 
     * @type {string}
     * @memberof CampaignStatusError
     */
    'idem'?: string;
    /**
     * 
     * @type {string}
     * @memberof CampaignStatusError
     */
    'job_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CampaignStatusError
     */
    'retry_at'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CampaignStatusError
     */
    'state'?: string;
}
/**
 * 
 * @export
 * @interface CampaignStatusErrorError
 */
export interface CampaignStatusErrorError {
    /**
     * 
     * @type {string}
     * @memberof CampaignStatusErrorError
     */
    'code'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CampaignStatusErrorError
     */
    'hint'?: string | null;
}
/**
 * 
 * @export
 * @interface CommitRequest
 */
export interface CommitRequest {
    /**
     * 
     * @type {number}
     * @memberof CommitRequest
     */
    'expected_jobs'?: number;
}
/**
 * 
 * @export
 * @interface CommitResponse
 */
export interface CommitResponse {
    /**
     * 
     * @type {string}
     * @memberof CommitResponse
     */
    'campaign_id': string;
    /**
     * 
     * @type {number}
     * @memberof CommitResponse
     */
    'expected_jobs': number;
    /**
     * 
     * @type {string}
     * @memberof CommitResponse
     */
    'state': string;
}
/**
 * 
 * @export
 * @interface ErrorResponse
 */
export interface ErrorResponse {
    /**
     * 
     * @type {ErrorResponseError}
     * @memberof ErrorResponse
     */
    'error': ErrorResponseError;
}
/**
 * 
 * @export
 * @interface ErrorResponseError
 */
export interface ErrorResponseError {
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseError
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseError
     */
    'message': string;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Bulk enqueue jobs (NDJSON)
         * @param {string} id Campaign ID
         * @param {string} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkEnqueueJobs: async (id: string, body: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('bulkEnqueueJobs', 'id', id)
            // verify required parameter 'body' is not null or undefined
            assertParamExists('bulkEnqueueJobs', 'body', body)
            const localVarPath = `/campaigns/{id}/jobs/bulk`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/x-ndjson';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Commit campaign uploads and enable processing
         * @param {string} id Campaign ID
         * @param {CommitRequest} [commitRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        commitCampaign: async (id: string, commitRequest?: CommitRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('commitCampaign', 'id', id)
            const localVarPath = `/campaigns/{id}/commit`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(commitRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create campaign
         * @param {CampaignCreate} campaignCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCampaign: async (campaignCreate: CampaignCreate, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'campaignCreate' is not null or undefined
            assertParamExists('createCampaign', 'campaignCreate', campaignCreate)
            const localVarPath = `/campaigns`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(campaignCreate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get campaign status
         * @param {string} id Campaign ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCampaignStatus: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getCampaignStatus', 'id', id)
            const localVarPath = `/campaigns/{id}/status`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get campaign status by external ID
         * @param {string} externalId External ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCampaignStatusByExternalId: async (externalId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'externalId' is not null or undefined
            assertParamExists('getCampaignStatusByExternalId', 'externalId', externalId)
            const localVarPath = `/campaigns/external/{external_id}/status`
                .replace(`{${"external_id"}}`, encodeURIComponent(String(externalId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Bulk enqueue jobs (NDJSON)
         * @param {string} id Campaign ID
         * @param {string} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async bulkEnqueueJobs(id: string, body: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BulkResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.bulkEnqueueJobs(id, body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.bulkEnqueueJobs']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Commit campaign uploads and enable processing
         * @param {string} id Campaign ID
         * @param {CommitRequest} [commitRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async commitCampaign(id: string, commitRequest?: CommitRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommitResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.commitCampaign(id, commitRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.commitCampaign']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create campaign
         * @param {CampaignCreate} campaignCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createCampaign(campaignCreate: CampaignCreate, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CampaignCreateResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createCampaign(campaignCreate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.createCampaign']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get campaign status
         * @param {string} id Campaign ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCampaignStatus(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CampaignStatus>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCampaignStatus(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getCampaignStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get campaign status by external ID
         * @param {string} externalId External ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCampaignStatusByExternalId(externalId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CampaignStatus>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCampaignStatusByExternalId(externalId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getCampaignStatusByExternalId']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Bulk enqueue jobs (NDJSON)
         * @param {string} id Campaign ID
         * @param {string} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkEnqueueJobs(id: string, body: string, options?: RawAxiosRequestConfig): AxiosPromise<BulkResult> {
            return localVarFp.bulkEnqueueJobs(id, body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Commit campaign uploads and enable processing
         * @param {string} id Campaign ID
         * @param {CommitRequest} [commitRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        commitCampaign(id: string, commitRequest?: CommitRequest, options?: RawAxiosRequestConfig): AxiosPromise<CommitResponse> {
            return localVarFp.commitCampaign(id, commitRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create campaign
         * @param {CampaignCreate} campaignCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCampaign(campaignCreate: CampaignCreate, options?: RawAxiosRequestConfig): AxiosPromise<CampaignCreateResponse> {
            return localVarFp.createCampaign(campaignCreate, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get campaign status
         * @param {string} id Campaign ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCampaignStatus(id: string, options?: RawAxiosRequestConfig): AxiosPromise<CampaignStatus> {
            return localVarFp.getCampaignStatus(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get campaign status by external ID
         * @param {string} externalId External ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCampaignStatusByExternalId(externalId: string, options?: RawAxiosRequestConfig): AxiosPromise<CampaignStatus> {
            return localVarFp.getCampaignStatusByExternalId(externalId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Bulk enqueue jobs (NDJSON)
     * @param {string} id Campaign ID
     * @param {string} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public bulkEnqueueJobs(id: string, body: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).bulkEnqueueJobs(id, body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Commit campaign uploads and enable processing
     * @param {string} id Campaign ID
     * @param {CommitRequest} [commitRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public commitCampaign(id: string, commitRequest?: CommitRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).commitCampaign(id, commitRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create campaign
     * @param {CampaignCreate} campaignCreate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public createCampaign(campaignCreate: CampaignCreate, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).createCampaign(campaignCreate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get campaign status
     * @param {string} id Campaign ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getCampaignStatus(id: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getCampaignStatus(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get campaign status by external ID
     * @param {string} externalId External ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getCampaignStatusByExternalId(externalId: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getCampaignStatusByExternalId(externalId, options).then((request) => request(this.axios, this.basePath));
    }
}



